### ISSUE TITLE
lonely SortTest.java

### ISSUE THREAD

**Issue by markuswagnergithub** [gintool/gin#6] opened 2017-09-20 11:37 UTC
There is a lonely SortTest.java in examples/locoGP

**Comment by drdrwhite** [comment] 2017-10-05 16:56
@codykenb is this there for a reason? Can we safely remove it?

**Comment by codykenb** [comment] 2017-10-05 17:11
It can be safely removed. It's there as I wanted all sort test cases to subclass this one. The test cases for each sort algorithm only differ by the sort algorithm method they call.

**Comment by drdrwhite** [comment] 2017-10-09 08:50
Shouldn't we fix it to incorporate the superclass?

**Comment by drdrwhite** [comment] 2017-10-09 08:51
Ah, I see a comment in Slack regarding this: 

codykenny [6:27 PM] 
We might need to extend gin to load the super type?

Did you try using a superclass previously?

**Comment by codykenb** [comment] 2017-10-09 10:01
Yes I tried subclassing the tests for each sort from SortTest but no individual was compiling. I couldn't see exactly the problem, but I can see where the [Test.class is read in](https://github.com/gintool/gin/blob/829626969f2d4765745407c9de3c6ed2c54b40f1/src/test/java/gin/TestRunnerTest.java#L113). 

Ideally we should load the superclass, and this is something that will likely be handy when we tackle larger programs with more tests. It might be a good idea to do this when designing the loading of multiple java files ? (The functionality exists as part of eclipse, but maybe there is something more lightweight?)

**Comment by drdrwhite** [comment] 2017-10-09 10:03
ok, I'll take a look later today, thanks.

**Comment by drdrwhite** [comment] 2017-10-09 17:11
Can confirm subclassing causes compile errors when running Gin on SortBubble

**Comment by drdrwhite** [comment] 2017-10-09 17:29
The problem is that Gin currently copies the test, along with the source, to a new folder for compilation. It _doesn't_ copy any other classes, so the test superclass is not found by the compiler. A fix will request us thinking hard about how to make Gin multi-file. Suggest we discuss on Slack and come back.

**Comment by drdrwhite** [comment] 2017-10-30 17:59
This is going to have to be fixed by multiclass capability, raised as another issue #10

**Comment by sandybrownlee** [comment] 2020-09-01 08:40
No longer relevant...

**Closed by sandybrownlee** 2020-09-01 08:40 UTC
Labels: enhancement
